title: Naufal Ramadhan
logo: /assets/img/Sirius.jpg
description:
  <a href="https://www.linkedin.com/in/naufal-ramadhan-723022128"> LinkedIn </a>
  <br></br>
  <a href="https://github.com/Naufal2112"> Github </a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal